services:
  - type: web
    name: job-board
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn jobBoard.wsgi"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jobboard-db
          property: connectionString

databases:
  - name: jobboard-db
    plan: free
